i18n/en.pot, src/App.js, src/helpers/feedbackSnackBarTypes.js, src/i18n.js, src/pages/Page.js
Passing page state through context.
Feedback Snackbar Types should be exposed by d2-ui, however it does not happen currently, we will have to create PR on d2-ui for that.
=> Flow fix and Feedback Snackbar Types

package.json, src/utils/api.js, yarn.lock
Some on context on what led to this PR:
- After upgrading the d2 package to 31.4, which was needed for bi-weekly period type support, `getReportingRateSummaryReport` kept returning empty rows.
- This turned out to be the result of a change in d2, which caused `includeNumDen=true` to be appended to the query parameters of the request url. When removing this parameter, or changing it to `includeNumDen=false`, the correct data was returned.
- There currently is a bug in d2 which makes it impossible to set `includeNumDen` to false. I have submitted a PR to fix this here https://github.com/dhis2/d2/pull/201
- However, I also noticed in the d2 docs and codebase that calling `d2.analytics.aggregate.get(req)` spawns two requests instead of one. This is for caching purposes, but I don't think very …
=> fix(reporting-rate-summary): fix get request

src/utils/api.js, src/utils/dom/loadScript.js
This fixes the `Uncaught SyntaxError: Unexpected token <` errors in `jquery.min.js:1` and `dhis2.util.js:1`. These errors actually meant that the file was not found, so we needed to fix them. We are now using an absolute path. I think it should work in production too.
=> fix(html reports): full paths to jquery and dhis.utils

src/components/SearchablePagedList.js, src/pages/Resource.js, src/pages/StandardReport.js, src/pages/resource/connectResource.js, src/redux/actions/__tests__/resource.test.js, src/redux/actions/resource.js, src/redux/reducers/__tests__/resource.test.js, src/redux/reducers/__tests__/standardReport.test.js, src/redux/reducers/resource.js, src/redux/reducers/standardReport.js
- Lists are no longer cleared when loading. Instead the `SearchablePagedList` component makes sure to not render rows when the list is loading. I've done this to better deal with a failing delete scenario. So now, for example, if we try to delete an item, loading starts, and then if it fails, loading stops, and the original list is displayed.
- I also introduced a confirmation step in the delete resource process
- And also prevented the list from reloading when re-entering the page/route
=> fix(lists): improve behavior when deleting from lists

src/App.js, src/components/AppRouter.js, src/components/SectionHeadline.js, src/components/__tests__/AppRouter.test.js, src/components/__tests__/MenuElement.test.js, src/config/sections.config.js, src/pages/DataSetReport.js, src/pages/OrganisationUnitDistributionReport.js, src/pages/ReportingRateSummary.js, src/pages/Resource.js, src/pages/StandardReport.js, src/pages/home/Home.js, src/pages/home/Home.test.js, src/utils/getDocsUrl.js
1. I've moved the component rendering to the `AppRouter` component, where it belongs to.
1. Now there's no more passing through of the `sectionKey` as each section page component already knows which section it is, so it can make use of it directly. This simplifies the router quite a bit!
1. Also the configuration of sections and the section order are not mixed in one constant anymore, making it easier to access values.
=> refactor: router constants and implementation

src/components/form/Button.js, src/pages/resource/add-edit-resource/ResourceForm.js, src/pages/resource/add-edit-resource/ResourceForm/Actions.js
This PR ensures that the save button is disabled when the resource form has invalid values
=> fix(resource): disable submit button if form is invalid

src/pages/standard-report/AddEditStdReport.js, src/pages/standard-report/add-edit-report/DesignFileDownloadButton.js, src/pages/standard-report/standard.report.conf.js
We used to call an old .action endpoint to get the default report templates, but Lars now introduced proper api endpoints for this.
Note:
The change in `AddEditStdReport` is an related bug-fix, which caused the `DesignFileDownloadButton` to always be in edit-mode
=> DHIS2-6525: download default report templates via webapi

src/components/ReportLoader.js, src/components/SectionHeadline.js, src/components/__tests__/__snapshots__/ReportLoader.test.js.snap, src/pages/DataSetReport.js, src/pages/OrganisationUnitDistributionReport.js, src/pages/ReportingRateSummary.js, src/utils/styles/shared.js
The report content and the loader now renders a separate Paper dev. I've also updated the relevant snapshots.
=> feat(reports): render report content and loader in a separate Paper div

src/components/AvailableOrganisationUnitsTree.js, src/components/__tests__/__snapshots__/AvailableOrganisationUnitsTree.test.js.snap
400px seems a good size: you can still see all un-expanded leaves of the base-node and once you start expanding a lot, a scroll bar will appear.
=> fix(available-org-unit-tree): set max-height of 400px

src/redux/actions/standardReport.js, src/utils/standardReport/index.js
We were sending an object of values that were selected, but this doesn't trigger deselection of the other values on the server.
We are now iterating over all boolean properties that are present in the state and determining for each property if its state-value is different from the form-value. If so, we include it in the payload object. This way values can be set and unset.
=> fix(standard-reports): unset boolean values correctly

src/pages/standard-report/add-edit-report/DesignFileDownloadButton.js
The links to the XML files will still have the download attribute, but for HTML files I'm omitting it.
=> fix(standard-reports): remove download attribute to avoid chrome issue

package.json
This is the hardcoded fix we discussed. I've tested locally against a v32 instance and that was working just fine.
=> fix: downgrade api version to v32 for dhis2-core v32

src/index.js
This is the switch to unversioned calls we discussed.
I was considering cleaning things up q bit more by removing the manifest from `package.json` and reading the `baseUrl` differently. But then I thought it might be better to do that when we uneject this app. And we won't be unejecting until we've swapped our styled-jsx stuff with CSS Modules. So in the end, I only implemented unversioned api calls.
=> fix: switch to unversioned api calls

src/utils/api.js, src/utils/api/helpers.js
Previously, when we were doing versioned API calls, when we called the `d2` Api `get` method with an url like this `../api/32/etc` it would actually do a GET request to `../api/api/32/etc`. We fixed this in https://github.com/dhis2/reports-app/commit/f315b8cd01ece66d5c9d8062c5b2a0602bcd205f by introducing the `sanitizeApiUrl` function (hack).
But it turns out that this behaviour doesn't happen when doing unversioned calls, so we can now remove the `sanitizeApiUrl` hack.
=> fix: response-rate-summary requests

src/utils/standardReport/index.js
This is to go into the 2.34.0 release
=> fix(standard-report): prevent error when stateValues are undefined 34.0

src/AppWrapper.js, src/utils/injectTranslationsToD2.js
I was importing `injectTranslationsToD2` before I was importing `./locales`. The result was that the resources for the user-locale hadn't been added yet when this `injectTranslationsToD2` was imported and it's calls to `i18n.t` were happening.
So moving the import to `./locales` fixed this.
=> fix: import ./locales before anything else so i18 has the correct locale

src/AppWrapper.js
Quite likely a regression due to upgrading `d2` or switching to the `useD2` helper. The problem was that once deployed, the `get` method on the `d2` `API` class was being supplied with a relative url (starting with `../`) that also included `/api`, i.e. `../api/`. In `d2` the relative urls get prefixed with the `baseUrl`, which was also set to `../api`. The result is a GET request to `api/api`.
I've tested this fix both for development-mode, where the `baseUrl` is an absolute url like `localhost:8080/api`, and also for deployed apps, where the `baseUrl` is a relative url, i.e. `../api`, and didn't find any issues.
=> fix(reporting-rate-summary): prevent `../api/api/<version>` urls

src/AppWrapper.js
This is simply a backport of https://github.com/dhis2/reports-app/pull/165
=> fix: let d2 make un-versioned api calls so urls don't break - v35 patch

src/pages/data-set-report/DataSetReportOutput.js, src/pages/standard-report/HtmlReport.js, src/pages/standard-report/HtmlReportAssets.js
We used to inject HTML into a div and applied some styles to its content. Now we are injecting the HTML into an iframe and these styles were gone. In this PR I've started injecting equivalent CSS into the iframe (and I removed the old styled-jsx styles because that was basically stale code).
Also, I added a small fix for #136. This is very unobtrusive, I only attached an extra sandbox attribute to the iframe.
=> fix(html-report): inject page styles into iframe

src/utils/standardReport/index.js
This is more like the code we had in 2.34.1, which wasn't looking at the report-type to determine which reportParams to use. Apparently where we need to look for report-params isn't tied as closely to the report-type as I was assuming.
=> fix(report-params): only use report.reportTable.reportParams if present

src/redux/reducers/dataSetDimensions.js
See [DHIS2-15041](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15041)
Updates api request to not includes filters that have been selected and then cleared
[DHIS2-15041]: https://dhis2.atlassian.net/browse/DHIS2-15041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: clear selected dimension if selection is null [DHIS2-15041]

src/utils/api.js
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15651
This changes reports app to display the organisation unit tree based on the user's organisation units for data display/analysis (rather than those for data capture). As this deals with data analysis, I checked in with the analytics team and Scott agreed that there wasn't a reason to be restricting users to the data capture organisation units for any of the report types in the Reports app.
=> fix: use data view organisation units [DHIS-15651]

src/redux/selectors/reportPeriod/periodTypes.js, src/utils/periods/fixedPeriods.js
Implements [DHIS2-16199](https://dhis2.atlassian.net/browse/DHIS2-16199)
[DHIS2-16199]: https://dhis2.atlassian.net/browse/DHIS2-16199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: missing labels in report period selector

src/redux/selectors/standardReport/getEditFormInitialValues.js
Since the changes[ in this PR:](https://github.com/dhis2/dhis2-core/pull/18691), reports' relative periods come back as undefined if a report does not have a relative period (while before they where returned as empty objects). In this PR i allow for both responses
=> fix: expect relative periods to be either undefined or an object

src/redux/actions/__tests__/standardReport.test.js, src/redux/actions/standardReport.js, src/redux/selectors/standardReport/getEditFormInitialValues.js, src/utils/backwardCompatability.js
This fixes an issue with saving in the reports app where relativePeriods and reportParams were not being persisted. (See ticket: https://dhis2.atlassian.net/browse/DHIS2-19815)
There are two issues relating to this ticket:
- previously the app was not saving relativePeriods and reportParams on first definition (this is because, it was trying to construct the relativePeriods and reportParams object by looking at the metadata for selected response, but this only existed when you were in edit mode and had got a response from the backend with a definition of relativePeriods and reportParams) (this is not a new problem for v42, we had noticed it and not prioritised fixing it). [There are fixes in this PR to build these objects in new mode]
- as of v42, there is an issue where relativePeriods …
=> fix: clean up save with reports app [BETA-155] [DHIS2-19815]
